# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia_ace_services_a2f_v1.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'nvidia_ace_services_a2f_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import nvidia_ace_a2f_v1_pb2 as nvidia__ace__a2f__v1__pb2
from . import nvidia_ace_status_v1_pb2 as nvidia__ace__status__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n nvidia_ace_services_a2f_v1.proto\x12\x1anvidia_ace.services.a2f.v1\x1a\x17nvidia_ace_a2f_v1.proto\x1a\x1anvidia_ace_status_v1.proto2a\n\nA2FService\x12S\n\x0fPushAudioStream\x12\x1e.nvidia_ace.a2f.v1.AudioStream\x1a\x1c.nvidia_ace.status.v1.Status\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_ace_services_a2f_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_A2FSERVICE']._serialized_start=117
  _globals['_A2FSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
