# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import nvidia_ace_a2f_v1_pb2 as nvidia__ace__a2f__v1__pb2
from . import nvidia_ace_status_v1_pb2 as nvidia__ace__status__v1__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nvidia_ace_services_a2f_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2FServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushAudioStream = channel.stream_unary(
                '/nvidia_ace.services.a2f.v1.A2FService/PushAudioStream',
                request_serializer=nvidia__ace__a2f__v1__pb2.AudioStream.SerializeToString,
                response_deserializer=nvidia__ace__status__v1__pb2.Status.FromString,
                _registered_method=True)


class A2FServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PushAudioStream(self, request_iterator, context):
        """RPC to implement to send audio data to Audio2Face Microservice
        An example use for this RPC is a client pushing audio buffers to
        Audio2Face Microservice (server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2FServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushAudioStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PushAudioStream,
                    request_deserializer=nvidia__ace__a2f__v1__pb2.AudioStream.FromString,
                    response_serializer=nvidia__ace__status__v1__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia_ace.services.a2f.v1.A2FService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia_ace.services.a2f.v1.A2FService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2FService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushAudioStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/nvidia_ace.services.a2f.v1.A2FService/PushAudioStream',
            nvidia__ace__a2f__v1__pb2.AudioStream.SerializeToString,
            nvidia__ace__status__v1__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
